---
root: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    legacyDecorators: true

env:
  es6: true
  node: true

extends:
  - "@whitetrefoil/eslint-config/presets/js"
  - "@whitetrefoil/eslint-config/presets/node"
  - "@whitetrefoil/eslint-config/presets/ts"
  - "@whitetrefoil/eslint-config/presets/ts-with-type"

rules:
  "node/callback-return": [ 0 ]

overrides:
  - files:
    - "tests/**/*.ts"
    env:
      mocha: true
